version: "3.7"

services:
  proxy:
    image: traefik:2.2.11
    restart: unless-stopped
    networks:
      mhtnet-network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  website:
    image: michaelhettmer/website:latest
    hostname: website
    restart: unless-stopped
    networks:
      mhtnet-network:
    labels:
      traefik.tag: mhtnet
      com.centurylinklabs.watchtower.enable: "true"

  portainer:
    image: "portainer/portainer-ce:2.0.0-alpine"
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - "9000"
    networks:
      mhtnet-network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    labels:
      traefik.tag: mhtnet
      traefik.http.routers.portainer.service: portainer-svc
      traefik.http.services.portainer-svc.loadbalancer.server.port: 9000

  watchtower:
    image: containrrr/watchtower:1.0.2
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --interval 30 --cleanup --label-enable
    environment:
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: ${WATCHTOWER_SLACK_HOOK_URL}
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: "Watchtower"

  ofelia:
    image: mcuadros/ofelia:v0.3.1
    command: daemon --docker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      ofelia.slack-webhook: ${OFELIA_SLACK_HOOK_URL}
      ofelia.job-run.gc.schedule: "@daily"
      ofelia.job-run.gc.container: "mhtnet_gc"

  gc:
    image: docker
    depends_on:
      - ofelia
    container_name: mhtnet_gc
    entrypoint: docker system prune -f
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  mhtnet-network:

volumes:
  portainer-data:
