version: "3.7"

services:
  proxy:
    image: traefik:v2.1.3
    restart: unless-stopped
    networks:
      mhtnet-network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  website:
    image: michaelhettmer/website:latest
    hostname: website
    restart: unless-stopped
    networks:
      mhtnet-network:
    labels:
      traefik.tag: mhtnet
      com.centurylinklabs.watchtower.enable: "true"

  portainer:
    image: "portainer/portainer-ce:2.0.0-alpine"
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - "9000"
    networks:
      mhtnet-network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    labels:
      traefik.tag: mhtnet
      traefik.http.services.portainer-svc.loadbalancer.server.port: 9000
      traefik.http.routers.portainer.service: portainer-svc

  watchtower:
    image: containrrr/watchtower:1.0.2
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --interval 30 --cleanup --label-enable

  ofelia:
    image: mcuadros/ofelia:v0.3.0
    command: daemon --docker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-local.daily-prune-job.schedule: "@daily"
      ofelia.job-local.daily-prune-job.command: "docker system prune --volumes --all -f"

networks:
  mhtnet-network:

volumes:
  portainer-data:
