version: "3.7"

services:
  proxy:
    image: traefik:v2.1.3
    restart: unless-stopped
    networks:
      mhtnet-network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  website:
    image: michaelhettmer/website:latest
    hostname: website
    restart: unless-stopped
    networks:
      mhtnet-network:
    labels:
      traefik.tag: mhtnet
      traefik.http.routers.website.service: website-svc
      com.centurylinklabs.watchtower.enable: "true"

networks:
  mhtnet-network:
