[[tls.certificates]]
  certFile = "/certs/mhtnet.pem"
  keyFile = "/certs/mhtnet.key"

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/certs/mhtnet.pem"
      keyFile = "/certs/mhtnet.key"
