[[tls.certificates]]
  certFile = "/certs/michael-hettmer.de.pem"
  keyFile = "/certs/michael-hettmer.de.key"

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/certs/michael-hettmer.de.pem"
      keyFile = "/certs/michael-hettmer.de.key"
